language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
    - add-on
    - extra
    - tools
script:
    - ./gradlew build
notifications:
  email: false
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
